export const STOCKINS_FETCH_SUCCESS = 'STOCKINS_FETCH_SUCCESS';
export const STOCKIN_IS_ADDED = 'STOCKIN_IS_ADDED';
export const STOCKIN_IS_VOIDED = 'STOCKIN_IS_VOIDED';
export const STOCKIN_HAS_ERRORED = 'STOCKIN_HAS_ERRORED';
// eslint-disable-next-line max-len
export const STOCKIN_IS_LOADING = 'STOCKIN_IS_LOADING';
export const STOCKIN_IS_PROCESSING = 'STOCKIN_IS_PROCESSING'; //CRUD
