export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const PRODUCT_IS_ADDED = 'PRODUCT_IS_ADDED';
export const PRODUCT_IS_UPDATED = 'PRODUCT_IS_UPDATED';
export const PRODUCT_IS_DELETED = 'PRODUCT_IS_DELETED';
export const PRODUCT_HAS_ERRORED = 'PRODUCT_HAS_ERRORED';
// eslint-disable-next-line max-len
export const PRODUCT_IS_LOADING = 'PRODUCT_IS_LOADING';
export const PRODUCT_IS_PROCESSING = 'PRODUCT_IS_PROCESSING'; //CRUD
