export const SUPPLIER_FETCH_SUCCESS = 'SUPPLIER_FETCH_SUCCESS';
export const SUPPLIER_IS_ADDED = 'SUPPLIER_IS_ADDED';
export const SUPPLIER_IS_UPDATED = 'SUPPLIER_IS_UPDATED';
export const SUPPLIER_IS_DELETED = 'SUPPLIER_IS_DELETED';
export const SUPPLIER_HAS_ERRORED = 'SUPPLIER_HAS_ERRORED';
// eslint-disable-next-line max-len
export const SUPPLIER_IS_LOADING = 'SUPPLIER_IS_LOADING';
export const SUPPLIER_IS_PROCESSING = 'SUPPLIER_IS_PROCESSING'; //CRUD
